### ISSUE TITLE
Manually adding a filter

### ISSUE THREAD

**Issue by iamkinetic** [relair/odata-data-source#4]
Is there a way to manually (by code) add a filter to a ODataDataSource? 

I know we can do : `this.dataSource.filters = [];`

But I can't find what I'm supposed to put in the list.

Thanks!

**Comment by relair** [comment]
It is explained at the bottom of the readme. It is expecting an array of objects conforming to ODataFilter interface.
Interface requires you to provide getFilter() function, that is supposed to return an object that follows this library: https://www.npmjs.com/package/odata-query#filtering
For example
`this.dataSource.filters = [{ getFilter: function() { 
    return { PropName: { contains: 'foo' } }
  }
}];`
will search filter entities on property 'PropName' containing 'foo'

**Comment by iamkinetic** [comment]
Thanks!
